### ISSUE TITLE
running ytdl_server.py

### ISSUE THREAD

**Issue by zeratax** [agiz/youtube-mpv#5]
When ever I try to run ytdl_server.py I get this:

```
➜  youtube-mpv-master python ytdl_server.py 
  File "ytdl_server.py", line 56
    print 'Unknown format. Cannot play video from:', yt_url
                                                  ^
SyntaxError: Missing parentheses in call to 'print'
➜  youtube-mpv-master python2 ytdl_server.py
Traceback (most recent call last):
  File "ytdl_server.py", line 4, in <module>
    import youtube_dl
ImportError: No module named youtube_dl
➜  youtube-mpv-master python3 ytdl_server.py
  File "ytdl_server.py", line 56
    print 'Unknown format. Cannot play video from:', yt_url
                                                  ^
SyntaxError: Missing parentheses in call to 'print'
```

The parentheses are just the start of errors though.

Edit: I ran 2to3 over this and that seemed to work for me.

**Comment by jamietanna** [comment]
What's your default version of Python? `ytdl_server.py` is a Python2 file, whereas `ytdl_server.py3` is a Python3 file.

**Comment by agiz** [comment]
That is right. ZerataX, it seems like a version mismatch issue.
